title: Welcome to my Page
author: Tony Le
Email: tonyle.1537@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
# social links
github_username:  Tonneh # DO NOT include the @ character, or else the build will fail!
Discord- Rice Farmer Tony#6282
show_excerpts: true # set to false to remove excerpts on the homepage
