title: Welcome to my Page
author: Tony Le
theme: jekyll-theme-cayman
description: > # this means to ignore newlines until "baseurl:"
  Socials: 
# social links
github_username:  Tonneh # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
